// This file was generated by Prisma, and assumes you have installed the following:\n// npm install --save-dev prisma dotenv\nimport 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    url: 'postgresql://postgres:postgres@db:5432/doomdev_db?schema=public',
  },
});
